export const INTENT_SET_EVENT_PROCESSOR = 'INTENT_SET_EVENT_PROCESSOR';
export const INTENT_SET_COMMAND_PROCESSOR = 'INTENT_SET_COMMAND_PROCESSOR';
export const INTENT_SET_STORE_PROCESSOR = 'INTENT_SET_STORE_PROCESSOR';
export const INTENT_CREATE_STORE = 'INTENT_CREATE_STORE';
export const INTENT_OBSERVE_STORE = 'INTENT_OBSERVE_STORE';
export const INTENT_PUSH_COMMAND = 'INTENT_PUSH_COMMAND';